#!/usr/bin/env node

import { gunzipSync, gzipSync } from "node:zlib";
import { readFile, writeFile } from "node:fs/promises";
import { minify } from "html-minifier-terser";

const [, , outputPath, ...inputPaths] = process.argv;

if (!outputPath || inputPaths.length === 0) {
  console.error(
    "Usage: node tools/build_web_assets.mjs OUTPUT_C INPUT_HTML...",
  );
  process.exit(2);
}

const minifyOptions = {
  collapseBooleanAttributes: true,
  collapseWhitespace: true,
  decodeEntities: true,
  minifyCSS: true,
  minifyJS: true,
  removeAttributeQuotes: true,
  removeComments: true,
  removeEmptyAttributes: true,
  removeOptionalTags: false,
  removeRedundantAttributes: true,
  sortAttributes: true,
  sortClassName: true,
  useShortDoctype: true,
};

function identifier(path) {
  const filename = path.split(/[\\/]/).at(-1) ?? path;
  return filename
    .replace(/\.html$/i, "")
    .replace(/[^a-zA-Z0-9_]/g, "_")
    .replace(/^([0-9])/, "_$1");
}

function formatBytes(bytes) {
  const rows = [];
  for (let offset = 0; offset < bytes.length; offset += 12) {
    const row = [...bytes.subarray(offset, offset + 12)]
      .map((byte) => `0x${byte.toString(16).padStart(2, "0")}`)
      .join(", ");
    rows.push(`  ${row},`);
  }
  return rows.join("\n");
}

const assets = [];
for (const inputPath of inputPaths) {
  const source = await readFile(inputPath, "utf8");
  const compact = await minify(source, minifyOptions);
  const compressed = gzipSync(Buffer.from(compact), {
    level: 9,
    mtime: 0,
  });
  if (!gunzipSync(compressed).equals(Buffer.from(compact))) {
    throw new Error(`gzip round-trip verification failed: ${inputPath}`);
  }
  assets.push({
    name: identifier(inputPath),
    sourceLength: Buffer.byteLength(source),
    compactLength: Buffer.byteLength(compact),
    compressed,
  });
}

const definitions = assets
  .map(
    ({ name, compressed }) => `const uint8_t yaogui_${name}_html_gz[] = {
${formatBytes(compressed)}
};
const size_t yaogui_${name}_html_gz_size =
    sizeof(yaogui_${name}_html_gz);`,
  )
  .join("\n\n");

const output = `/* Generated by tools/build_web_assets.mjs. Do not edit. */
#include <stddef.h>
#include <stdint.h>

${definitions}
`;

await writeFile(outputPath, output);

for (const asset of assets) {
  console.log(
    `${asset.name}.html: ${asset.sourceLength} -> ${asset.compactLength} -> ` +
      `${asset.compressed.length} bytes (source -> minified -> gzip)`,
  );
}
