#!/usr/bin/env python3
"""Minify HTML markup and generate reproducible gzip-backed C assets."""

from __future__ import annotations

import argparse
import gzip
import io
import re
from pathlib import Path


PROTECTED_BLOCK = re.compile(
    r"(<(?:script|style)\b[^>]*>.*?</(?:script|style)>)",
    re.IGNORECASE | re.DOTALL,
)
HTML_COMMENT = re.compile(r"<!--(?!\[if\b).*?-->", re.IGNORECASE | re.DOTALL)
BETWEEN_TAGS = re.compile(r">\s+<")
WHITESPACE = re.compile(r"\s+")


def minify_html(source: str) -> str:
    """Compact HTML text while preserving inline CSS and JavaScript verbatim."""
    parts = PROTECTED_BLOCK.split(source)
    for index in range(0, len(parts), 2):
        part = HTML_COMMENT.sub("", parts[index])
        part = BETWEEN_TAGS.sub("><", part)
        parts[index] = WHITESPACE.sub(" ", part).strip()
    return "".join(parts)


def gzip_reproducible(data: bytes) -> bytes:
    output = io.BytesIO()
    with gzip.GzipFile(
        filename="", mode="wb", fileobj=output, compresslevel=9, mtime=0
    ) as stream:
        stream.write(data)
    compressed = bytearray(output.getvalue())
    compressed[9] = 255
    if gzip.decompress(compressed) != data:
        raise RuntimeError("gzip round-trip verification failed")
    return bytes(compressed)


def identifier(path: Path) -> str:
    name = re.sub(r"[^a-zA-Z0-9_]", "_", path.stem)
    return f"_{name}" if name[:1].isdigit() else name


def format_bytes(data: bytes) -> str:
    return "\n".join(
        "  " + ", ".join(f"0x{byte:02x}" for byte in data[offset : offset + 12]) + ","
        for offset in range(0, len(data), 12)
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    parser.add_argument("inputs", type=Path, nargs="+")
    args = parser.parse_args()

    definitions: list[str] = []
    for input_path in args.inputs:
        source = input_path.read_text(encoding="utf-8")
        compact = minify_html(source)
        compressed = gzip_reproducible(compact.encode("utf-8"))
        name = identifier(input_path)
        definitions.append(
            f"""const uint8_t yaogui_{name}_html_gz[] = {{
{format_bytes(compressed)}
}};
const size_t yaogui_{name}_html_gz_size =
    sizeof(yaogui_{name}_html_gz);"""
        )
        print(
            f"{input_path.name}: {len(source.encode('utf-8'))} -> "
            f"{len(compact.encode('utf-8'))} -> {len(compressed)} bytes "
            "(source -> minified -> gzip)"
        )

    args.output.write_text(
        "/* Generated by tools/build_web_assets.py. Do not edit. */\n"
        "#include <stddef.h>\n"
        "#include <stdint.h>\n\n"
        + "\n\n".join(definitions)
        + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
